/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 开通租户(平台级,platform_admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 取租户详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 部分更新租户(平台运维:停用/恢复/改名;platform_admin only,租户管理员不可改自身) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TenantPatch"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/tenants/{tid}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出本租户用户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/apps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出应用 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["App"][];
                    };
                };
            };
        };
        put?: never;
        /** 注册应用(ZTNA) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["App"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["App"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出连接器 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Connector"][];
                    };
                };
            };
        };
        put?: never;
        /** 注册连接器 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Connector"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Connector"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出本租户编写态策略(Slice58;platform_admin 经 path-tid RLS 可读任意租户) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建策略(编写态) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/policies/compile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 编译并原子激活策略(产 PolicyBundle;幂等) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompileResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/policies/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 取当前激活的 PolicyBundle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompileResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 签发短 TTL 会话凭证 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IssueCredentialRequest"];
                };
            };
            responses: {
                /** @description 已签发 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssueCredentialResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/credentials/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 按 jti 撤销凭证(秒级失效) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RevokeCredentialRequest"];
                };
            };
            responses: {
                /** @description 已撤销 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusJTI"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 读本租户审计日志(只读;auditor 可读) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /**
         * 列本租户全部风险评分快照(只读;score 降序、subject 升序;platform_admin 经 path-tid RLS 可读任意租户)
         * @description 风险引擎持久化快照层(评分变更后 best-effort upsert)。**权威评分态在内存**,本端点暴露全部最新落库快照。
         *     快照持久化未启用 → 503;空租户 → 空数组 []。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RiskScore"][];
                    };
                };
                /** @description risk 服务未配置或快照持久化未启用 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/risk/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
                /** @description 主体(用户/设备身份) */
                subject: string;
            };
            cookie?: never;
        };
        /**
         * 取某主体最新风险评分快照(只读;platform_admin 经 path-tid RLS 可读任意租户)
         * @description 风险引擎持久化快照层(评分变更后 best-effort upsert)。**权威评分态在内存**,本端点暴露最新落库快照。
         *     快照持久化未启用 → 503;该主体无快照 → 404。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 主体(用户/设备身份) */
                    subject: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RiskScore"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description risk 服务未配置或快照持久化未启用 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/idp/configs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出 IdP 配置(不含 client_secret) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdPConfig"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建 IdP 配置(client_secret 经租户 DEK 加密落库,secret 模块首个加密消费者) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateIdPConfigRequest"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdPConfig"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 租户 DEK 未就绪或已销毁(无法加密) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/idp/configs/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
                cid: string;
            };
            cookie?: never;
        };
        /** 取 IdP 配置详情(不含 client_secret) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdPConfig"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 删除 IdP 配置(audit_tr 留痕) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    cid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** 部分更新 IdP 配置(可选改 client_secret) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    cid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateIdPConfigRequest"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IdPConfig"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                /** @description DEK 已销毁 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/tenants/{tid}/swg/rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出 SWG 规则 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SWGRule"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建 SWG 规则(URL 过滤) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SWGRule"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SWGRule"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/swg/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
                /** @description 规则 ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 全量替换 SWG 规则(改规则与建规则同等校验) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 规则 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SWGRule"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SWGRule"];
                    };
                };
                /** @description 校验失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 规则不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 删除 SWG 规则 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 规则 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 规则不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/sites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出站点 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Site"][];
                    };
                };
            };
        };
        put?: never;
        /** 注册站点(SD-WAN) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Site"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/fw/rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出 FWaaS 规则 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FWRule"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建 FWaaS 规则(L3/L4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FWRule"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FWRule"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/fw/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
                /** @description 规则 ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 全量替换 FWaaS 规则(改规则与建规则同等校验) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 规则 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FWRule"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FWRule"];
                    };
                };
                /** @description 校验失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 规则不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 删除 FWaaS 规则 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 规则 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 规则不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/dlp/rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出 CASB-DLP 规则 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DLPRule"][];
                    };
                };
            };
        };
        put?: never;
        /** 创建 CASB-DLP 规则 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DLPRule"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DLPRule"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/dlp/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
                /** @description 规则 ID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 全量替换 CASB-DLP 规则(改规则与建规则同等校验) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 规则 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DLPRule"];
                };
            };
            responses: {
                /** @description 已更新 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DLPRule"];
                    };
                };
                /** @description 校验失败 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 规则不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** 删除 CASB-DLP 规则 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                    /** @description 规则 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 规则不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 生成 ZTP 一次性激活码(connector / cpe) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEnrollmentRequest"];
                };
            };
            responses: {
                /** @description 已生成 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivationCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        /** 列出本租户已登记设备(ZTP 可见性;只读;只含非敏感字段,不含激活码;platform_admin 经 path-tid RLS 可读任意租户) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tid}/devices/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销设备(撤销后续期被拒) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RevokeDeviceRequest"];
                };
            };
            responses: {
                /** @description 已撤销 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusIdentity"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 跨租户列出全租户摘要(平台运维,platform_admin;经 InPlatformTx 读策展视图) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tid}/decommission": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标注租户进入注销宽限期(软删→宽限→硬删 DEK;platform_admin only;对已 offboarding 租户重复调用会顺延宽限期末) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DecommissionRequest"];
                };
            };
            responses: {
                /** @description 已进入注销宽限期 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/tenants/{tid}/decommission/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 租户 ID(UUID) */
                tid: components["parameters"]["Tid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 宽限期内取消注销(回 active;platform_admin only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 租户 ID(UUID) */
                    tid: components["parameters"]["Tid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已取消注销 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tenant"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description 租户不在注销宽限期 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/decommissions/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 硬删自动清扫(扫描宽限期已到的租户:DEK 销毁 + 状态→decommissioned;platform_admin only)
         * @description 串起 Slice33c(注销宽限期)与 Slice34(secret DEK 销毁)的端到端硬删:
         *     ① 经平台路径跨租户列 status='offboarding' AND decommission_at<now 的租户;
         *     ② 每条:secret.DestroyTenantKey(DEK 销毁,**L1 3.16 不可逆**)→ tenant.Update status=decommissioned。
         *     两步各自原子幂等→**重跑安全**;失败租户进 skipped 不阻塞其它。
         *     **诚实状态:** 当前无业务数据用 DEK 加密(Slice34 基础设施先于消费者),DEK 销毁此刻是符号性的;
         *     待首个加密消费者(IdPConfig 等)接入,本端点完成后数据将真正不可恢复。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 扫描完成(可能 0 条 due) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DecommissionSweepResult"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/admin-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 平台签发 admin 令牌(临时机制,platform_admin only)
         * @description 本端点为 IdP-based 管理员登录到位前的**临时机制**:平台 mint 签名令牌(≤12h TTL,Role+TenantID claim)。
         *     **支持 role**(Slice38c 起):
         *       - `tenant_admin` / `auditor` — **必带 `tenant_id`**(作用域租户;审计落 target tenant);
         *       - `platform_admin`(Slice38c)— **必查 `platform_admins` 表 IsActive(subject)** + **必空 `tenant_id`**(跨租户);
         *         subject 不在表/disabled → 403;RBAC 服务未配置(SASE_DB_PLATFORM_RW_DSN 未设)→ 503;**bootstrap env 绕过本表**(应急通道,生产应立即用该令牌 POST /platform/admins 登记自己)。
         *     **disable/delete platform_admin 即时撤销已签出令牌(Slice56)**:authz 中间件对 platform_admin 令牌**每请求复查 IsActive(subject)**,disable/delete 后该 subject 令牌即 401(无需等 TTL)。bootstrap 豁免(不在表)。**注**:撤销基于当前 active 状态(非按签发时刻),故 disable 后再 enable / delete 后再建同名 subject 会使旧令牌恢复有效——属有意运维动作。
         *     **detail 审计只记 subject+role,不记 token**(凭证泄露面)。生产终态应走 IdP→换令牌。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IssueAdminTokenRequest"];
                };
            };
            responses: {
                /** @description 已签发 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IssueAdminTokenResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description 调用者非 platform_admin / platform_admin subject 不在 RBAC 表/disabled */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description platform RBAC 未配置(role=platform_admin 路径需) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/pop-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列 PoP 节点(平台运维/前端容量看板数据源) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PoP 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PoP"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 平台写池未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * 新建 PoP 节点(platform_admin only;Slice38a / PC-API-3)
         * @description PoP = 平台级共享基础设施(非租户数据,无 tenant_id);写经 app_platform_rw 专用池。
         *     `name` UNIQUE 防重(409 ErrPopAlreadyExists);**name/region/endpoint 不可后续修改**(防 ID 漂移)。
         *     未配 SASE_DB_PLATFORM_RW_DSN → 503。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePopRequest"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PoP"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description name 已存在 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台写池未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/pop-nodes/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取单个 PoP 详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PoP */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PoP"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description PoP 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台写池未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新 PoP(仅 status / max_users 可改;name/region/endpoint 不可改) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PopPatch"];
                };
            };
            responses: {
                /** @description 更新后 PoP */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PoP"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description PoP 不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台写池未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/platform/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 平台级审计读端点(Slice39,与 tenant audit_log /api/v1/tenants/{tid}/audit 对称)
         * @description 平台级操作(PoP CRUD / 未来 CA·KEK / 平台 RBAC)的双层审计:**source=data**(DB 触发器
         *     platform_audit_row 业务事务内原子写,result=0 哨兵)+ **source=api**(handler 显式写,
         *     含失败 4xx/500,覆盖 2xx-零变更盲区)。authz 限 platform_admin。
         *     SASE_DB_PLATFORM_RW_DSN 未设 → 503。
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 审计列表(按 ts DESC) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformAuditEntry"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 平台审计未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列 platform_admin */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 管理员列表(按 created_at 升序) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformAdmin"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 平台 RBAC 未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * 新建 platform_admin(Slice38c,平台管理员持久化 RBAC)
         * @description 登记一枚 platform_admin 主体到 platform_admins 表;**该主体登记后才能经 `/platform/admin-tokens`
         *     签发 role=platform_admin 令牌**(bootstrap env 例外,应急通道)。authz 默认分支已限 platform_admin。
         *     SASE_DB_PLATFORM_RW_DSN 未设 → 503;subject 重复 → 409。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePlatformAdminRequest"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformAdmin"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description subject 已存在 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台 RBAC 未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/admins/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取 platform_admin 详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    aid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PlatformAdmin */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformAdmin"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 管理员不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台 RBAC 未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 删除 platform_admin(**禁止删除自己**防锁死;disable 也不可)
         * @description **delete 即时撤销已签出令牌(Slice56)**:authz 每请求复查 IsActive,delete 后该 subject 令牌即 401(无需等 TTL)。
         *     **防自助锁死**:删自己被拒(400)。**last-admin 保护(Slice55)**:删表内最后一枚 active 平台管理员被拒(400,事务内 FOR UPDATE 计数,防 TOCTOU)。删他人后,该 subject 后续无法再签发 platform_admin token。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    aid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                        };
                    };
                };
                /** @description 删自己被拒(用 PATCH disabled 替代) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 管理员不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台 RBAC 未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * 更新 platform_admin(status / email);subject 不可改
         * @description **disable 即时撤销已签出令牌(Slice56)**:authz 每请求复查 IsActive,disable 后该 subject 令牌即 401(无需等 TTL)。
         *     **防自助锁死**:disable 自己被拒(400);**last-admin 保护(Slice55)**:disable 表内最后一枚 active 平台管理员被拒(400,事务内 FOR UPDATE 计数,防 TOCTOU),防停用至 0 active 锁死。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    aid: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlatformAdminPatch"];
                };
            };
            responses: {
                /** @description 更新后 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformAdmin"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description 管理员不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 平台 RBAC 未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/trust/pubkey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取签发公钥(公开;pop-agent 引导用,公钥非密) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrustPubkey"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ZTP 兑换(公开;设备凭激活码 + CSR 换租户绑定证书;按 IP 限流) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RedeemRequest"];
                };
            };
            responses: {
                /** @description 已签发证书 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RedeemResponse"];
                    };
                };
                /** @description 限流(激活码枚举/暴力防护) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/idp/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IdP OIDC 登录入口(公开;303 跳 IdP authorize URL,PKCE S256)
         * @description 前端按 query `tenant_id` + `idp_id` 拼出此 URL 让浏览器跳转。
         *     服务端 ① 读 IdPConfig(必须 status=active)② 解密 client_secret(短窗内存)③ 生成 PKCE code_verifier + 服务端 state ID ④ 303 跳 IdP。
         *     SASE_OIDC_CALLBACK_URL 未设时 → 503(端点存在但未配置)。
         */
        get: {
            parameters: {
                query: {
                    tenant_id: string;
                    idp_id: string;
                    /**
                     * @description 登录成功后浏览器跳回的 SPA 路径(同源相对路径,以 / 开头但不以 // 开头,不含反斜杠);
                     *     不合规一律退默认 "/"(防 open-redirect 攻击);落服务端 state,客户端不能改。
                     */
                    return_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 跳 IdP authorize URL */
                303: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 缺/非法 query */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IdP 已禁用(status=disabled) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IdP 配置不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IdP 密钥不可用(DEK 销毁/未建) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OIDC discovery 失败(IdP 不可达/issuer 错) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OIDC 未配置(部署未启) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/idp/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * IdP OIDC 回调(公开;state TakeOnce → 换 token → EnsureUser → 签会话凭证)
         * @description 单一 callback URL 对所有租户/IdP 复用,租户/IdP 信息走服务端 state(不走 query → 防 CSRF + 跨租户切换)。
         *     **响应形态按 Accept 头分流(Slice37c)**:
         *       - **Accept 含 `text/html`(浏览器)** → 302 Location: rec.ReturnTo + Set-Cookie sase_session(httpOnly,SameSite=Lax);
         *       - **其它(API 客户端/curl/默认)** → 200 + JSON 会话凭证(向后兼容)。
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                    /** @description IdP 端拒绝/出错时回的标准 OAuth2 error 参数 */
                    error?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 会话凭证(默认/编程客户端) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OIDCCallbackResponse"];
                    };
                };
                /** @description 浏览器路径(Accept 含 text/html);跳 return_to + Set-Cookie sase_session */
                302: {
                    headers: {
                        Location?: string;
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description state 不存在/过期/缺 code/IdP 错 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IdP 认证失败(id_token 校验/userinfo 拒) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IdP 已禁用 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description IdP 密钥不可用 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OIDC discovery 失败 */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OIDC 未配置 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Tenant: {
            /**
             * Format: uuid
             * @description 留空则后端生成
             */
            id?: string;
            name: string;
            /** @enum {string} */
            status?: "active" | "suspended" | "offboarding";
            /** @description 加密档/订阅档(standard/gm/...,业务命名,后端不枚举校验) */
            plan?: string;
            /**
             * Format: date-time
             * @description 计划硬删时刻(注销宽限期末);null=未注销
             */
            decommission_at?: string | null;
            /** @description 用户数上限;null=不限 */
            max_users?: number | null;
            /** @description 策略数上限;null=不限 */
            max_policies?: number | null;
            /** @description 带宽上限 Mbps;null=不限 */
            max_bandwidth_mbps?: number | null;
        };
        /** @description 注销宽限期(可选;grace_hours<=0 或缺省 → 服务端默认 30 天) */
        DecommissionRequest: {
            /** @description 宽限期小时数;0/缺省用默认 */
            grace_hours?: number;
        };
        /**
         * @description 租户部分更新(PATCH 语义:不提供=不改;提供即设)。
         *     **配额语义**:0=完全限死(业务硬封顶,有意支持,运维须显式);>0=上限;不能表达"改回 null/不限"(LP-PC1 后续 clear-flag/sentinel)。
         */
        TenantPatch: {
            name?: string;
            /** @enum {string} */
            status?: "active" | "suspended" | "offboarding";
            plan?: string;
            max_users?: number;
            max_policies?: number;
            max_bandwidth_mbps?: number;
        };
        /** @description 平台跨租户只读策展视图字段(不含用户/策略明细) */
        TenantSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            status?: string;
            plan?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            decommission_at?: string | null;
            /** @description 用户数上限;null=不限 */
            max_users?: number | null;
            /** @description 策略数上限;null=不限 */
            max_policies?: number | null;
            /** @description 带宽上限 Mbps;null=不限 */
            max_bandwidth_mbps?: number | null;
        };
        User: {
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            /** @description IdP 侧主键 */
            external_id?: string;
            email?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
        };
        /** @description 设备入网记录的非敏感只读视图(ZTP 可见性);有意不含 activation_code(一次性激活码=秘密)。 */
        Device: {
            id?: string;
            /** @enum {string} */
            kind?: "connector" | "cpe";
            /** @description 签入证书 CommonName(connector app / cpe site_key) */
            identity?: string;
            /** @enum {string} */
            status?: "pending" | "redeemed" | "revoked";
            /**
             * Format: date-time
             * @description 兑换时刻;未兑换为 null
             */
            redeemed_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        App: {
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            app_key: string;
            name: string;
            upstream?: string;
        };
        Connector: {
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            app_key?: string;
            name?: string;
        };
        Policy: {
            id?: string;
            name?: string;
            priority?: number;
            /** @description group | device-posture | risk_gte | ... */
            subject_kind?: string;
            subject_value?: string;
            resource?: string;
            action?: string;
            /** @enum {string} */
            effect?: "allow" | "deny" | "inspect";
        };
        /** @description 编译/激活结果(PolicyBundle 摘要) */
        CompileResult: {
            /** Format: int64 */
            version?: number;
            content_hash?: string;
            /** @description false=内容未变、未产新版、未下发(幂等) */
            changed?: boolean;
        };
        AuditEntry: {
            /** Format: uuid */
            tenant_id?: string;
            /** Format: date-time */
            ts?: string;
            actor_subject?: string;
            actor_role?: string;
            /** @description api 源=HTTP 动作;data 源=TG_OP 表名 */
            action?: string;
            /** @description api 源=HTTP 码;data 源=0 哨兵 */
            result?: number;
            detail?: string;
            /**
             * @description api=HTTP 中间件 / data=DB 触发器(原子)
             * @enum {string}
             */
            source?: "api" | "data";
        };
        /** @description 风险评分快照(risk_scores 一行;最新落库快照,权威评分态在内存) */
        RiskScore: {
            subject?: string;
            /** @description 0–100 */
            score?: number;
            /** @enum {string} */
            level?: "low" | "medium" | "high" | "critical";
            /** @description 可解释因子(可空) */
            factors?: components["schemas"]["RiskFactor"][] | null;
            /**
             * Format: date-time
             * @description 快照落库时刻
             */
            updated_at?: string;
        };
        /** @description 一个风险贡献因子(可解释性/审计) */
        RiskFactor: {
            /** @description 如 posture:jailbroken_rooted / dlp:身份证 */
            id?: string;
            /** @description 对 score 的贡献 */
            weight?: number;
        };
        SWGRule: {
            /**
             * Format: uuid
             * @description 规则 ID(响应含;PUT/DELETE 经路径寻址)
             */
            readonly id?: string;
            kind?: string;
            pattern?: string;
            action?: string;
        };
        FWRule: {
            /**
             * Format: uuid
             * @description 规则 ID(响应含;PUT/DELETE 经路径寻址)
             */
            readonly id?: string;
            priority?: number;
            /** @enum {string} */
            action?: "allow" | "deny";
            /** @enum {string} */
            protocol?: "any" | "tcp" | "udp" | "icmp";
            src_cidr?: string;
            dst_cidr?: string;
            dst_port_min?: number;
            dst_port_max?: number;
        };
        DLPRule: {
            /**
             * Format: uuid
             * @description 规则 ID(响应含;PUT/DELETE 经路径寻址)
             */
            readonly id?: string;
            name?: string;
            /** @enum {string} */
            match_type?: "keyword" | "regex";
            pattern?: string;
            /** @enum {string} */
            action?: "block" | "alert";
            /** @enum {string} */
            severity?: "low" | "medium" | "high";
        };
        Site: {
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            site_key: string;
            name?: string;
            cidr: string;
        };
        DecommissionSweepResult: {
            /** @description 成功硬删的租户 id 列表 */
            processed?: string[];
            /** @description 失败/跳过的租户(各租户独立,不阻塞其它) */
            skipped?: {
                /** Format: uuid */
                tenant_id?: string;
                reason?: string;
            }[];
        };
        /** @description IdP 配置(**响应有意不含 client_secret**,防意外序列化;明文 secret 仅在 adapter 内部 GetClientSecret 取) */
        IdPConfig: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            name?: string;
            /**
             * @description IdP 形态(标准 OIDC + 三家国产 IdP:企微/钉钉/飞书均已落地,Slice37b-1/-2)
             * @enum {string}
             */
            kind?: "oidc" | "wecom" | "dingtalk" | "feishu";
            endpoint?: string;
            client_id?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            /**
             * @description 可选 IdP 私有化部署/灰度域名经此扩展字段配置(Slice37c):
             *       - wecom_auth_host    企微 authorize host(默认 https://open.weixin.qq.com)
             *       - dingtalk_oauth_host 钉钉 OAuth host(默认 https://login.dingtalk.com)
             *       - feishu_auth_host   飞书 authorize host(默认 https://accounts.feishu.cn)
             */
            extra?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateIdPConfigRequest: {
            name: string;
            /** @enum {string} */
            kind: "oidc" | "wecom" | "dingtalk" | "feishu";
            /** @description oidc=issuer URL;wecom=API base(空走 https://qyapi.weixin.qq.com);dingtalk=API base(空走 https://api.dingtalk.com);feishu=API base(空走 https://open.feishu.cn) */
            endpoint: string;
            /** @description oidc=client_id;wecom=corpid;dingtalk/feishu=app_id */
            client_id: string;
            /** @description 明文(oidc=client_secret;wecom=corpsecret;...);服务端 secret.Encrypt 加密落库后丢弃 */
            client_secret: string;
            extra?: {
                [key: string]: unknown;
            };
        };
        /** @description PATCH 语义:不提供=不改;client_secret 非空 → 重新加密落库 */
        UpdateIdPConfigRequest: {
            name?: string;
            endpoint?: string;
            client_id?: string;
            client_secret?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description 签发 admin 令牌请求。`tenant_id` **条件必填**:
         *       - `role ∈ {tenant_admin, auditor}` → 必填(作用域租户);
         *       - `role = platform_admin`(Slice38c)→ **必空**(跨租户),且 subject 必须在 platform_admins 表且 status=active。
         */
        IssueAdminTokenRequest: {
            /** @description 调用方 subject(将进入 admin 令牌 claim;platform_admin 路径必在 platform_admins 表) */
            subject: string;
            /**
             * @description 见上方 description 的条件必填规则
             * @enum {string}
             */
            role: "tenant_admin" | "auditor" | "platform_admin";
            /**
             * Format: uuid
             * @description 作用域租户(tenant_admin/auditor 必填;platform_admin 必空)
             */
            tenant_id?: string;
            /** @description TTL(秒);0/缺省/超 12h → 钳至 12h(MaxAdminTTL) */
            ttl_seconds?: number;
        };
        IssueAdminTokenResponse: {
            /** @description 签名 admin 令牌(cred 格式;不要进任何审计/日志 */
            token?: string;
            subject?: string;
            /** @enum {string} */
            role?: "tenant_admin" | "auditor";
            /** Format: uuid */
            tenant_id?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        IssueCredentialRequest: {
            user_id: string;
            groups?: string[];
            posture?: string;
            ttl_seconds?: number;
        };
        IssueCredentialResponse: {
            token?: string;
            jti?: string;
        };
        RevokeCredentialRequest: {
            jti: string;
            subject?: string;
            reason?: string;
        };
        StatusJTI: {
            status?: string;
            jti?: string;
        };
        CreateEnrollmentRequest: {
            /** @enum {string} */
            kind: "connector" | "cpe";
            /** @description 签入证书 CommonName(connector app / cpe site_key) */
            identity: string;
        };
        ActivationCode: {
            activation_code?: string;
        };
        RevokeDeviceRequest: {
            identity: string;
        };
        StatusIdentity: {
            status?: string;
            identity?: string;
        };
        TrustPubkey: {
            alg?: string;
            /** @description base64url 公钥 */
            pubkey?: string;
        };
        RedeemRequest: {
            activation_code: string;
            /** @description 设备本地生成的 CSR(PEM;私钥不离设备) */
            csr_pem: string;
        };
        RedeemResponse: {
            /** @description 租户绑定证书(PEM) */
            cert_pem?: string;
        };
        /** @description PoP 节点(平台共享基础设施;无 tenant_id)。 */
        PoP: {
            /** Format: uuid */
            id: string;
            /** @description 运营标识(unique) */
            name: string;
            /** @description 地域 */
            region: string;
            /** @description PoP 入口公网地址 */
            endpoint: string;
            /** @description 容量上限(nil=未设) */
            max_users?: number | null;
            /** @enum {string} */
            status: "active" | "draining" | "down";
            /**
             * Format: date-time
             * @description heartbeat 最近时间(Slice38a 暂不写)
             */
            last_seen_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreatePopRequest: {
            name: string;
            region: string;
            endpoint: string;
            max_users?: number | null;
        };
        /** @description PATCH 语义(nil 不改)。仅 status/max_users 可改;name/region/endpoint 故意不可改(防 ID 漂移)。 */
        PopPatch: {
            /** @enum {string|null} */
            status?: "active" | "draining" | "down" | null;
            max_users?: number | null;
        };
        /** @description 平台管理员持久化记录(Slice38c)。 */
        PlatformAdmin: {
            /** Format: uuid */
            id: string;
            /** @description 主体标识(IdP sub / 运营 ID;UNIQUE) */
            subject: string;
            /** @description 联系邮箱(可空) */
            email?: string;
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @description 谁加的(审计;bootstrap 加自己时可空) */
            created_by?: string;
        };
        CreatePlatformAdminRequest: {
            subject: string;
            email?: string;
        };
        /** @description PATCH 语义(nil 不改);仅 status/email 可改;subject 故意不可改(主键级;改名 = 删后重建)。 */
        PlatformAdminPatch: {
            /** @enum {string|null} */
            status?: "active" | "disabled" | null;
            email?: string | null;
        };
        /** @description 平台审计记录(Slice39;与 tenant audit_log Entry 对称,无 tenant_id,可选 target_tenant_id)。 */
        PlatformAuditEntry: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            ts: string;
            /** @description 主体(空主体兜底 'system') */
            actor_subject: string;
            /** @description 角色(platform_admin / system / ...) */
            actor_role: string;
            /** @description API:如 "POST /api/v1/platform/pop-nodes";触发器:如 "INSERT pop_nodes" */
            action: string;
            /** @description HTTP 码(source=api)或 0(source=data 哨兵) */
            result: number;
            detail?: string;
            /** @enum {string} */
            source: "api" | "data";
            /**
             * Format: uuid
             * @description 可选;平台对某租户操作时关联
             */
            target_tenant_id?: string;
        };
        /** @description OIDC 回调成功返回的 SASE 会话凭证(短 TTL,L1 3.8)。 */
        OIDCCallbackResponse: {
            /** @description SASE 自签会话凭证(Bearer) */
            token: string;
            /** @description 凭证 ID(撤销按此键) */
            jti: string;
            /**
             * Format: int32
             * @description TTL 秒
             */
            expires_in: number;
            /**
             * Format: uuid
             * @description SASE 用户 ID(IdP subject 经 EnsureUserByExternalID 映射)
             */
            user_id: string;
            /** @description 邮箱(IdP 返回 */
            email?: string;
        };
    };
    responses: {
        /** @description 请求非法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 未认证(无/无效 Bearer 令牌) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 越权(authz 后端拒绝) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 未找到 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description 租户 ID(UUID) */
        Tid: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
