// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sase/control/v1/control.proto

// 包 sase.control.v1:Agent↔控制面 的终端实时控制通道契约(ZTNA 硬化 L2 3.4 层②"端提速")。

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControl_Channel_FullMethodName = "/sase.control.v1.AgentControl/Channel"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentControl 是 Agent↔控制面 的持久双向流(终端实时控制)。
// 权威仍在 PoP(吊销表 + 短 TTL,ZTNA 硬化 L2 3.4 层①③);本通道仅加速端侧反应(层②),best-effort:
// 通道断/丢消息不影响安全——PoP 仍按吊销表+短 TTL 兜底。
type AgentControlClient interface {
	// Channel:Agent 建立长连,首条 AgentEvent{kind=hello,token} 注册身份;
	// 之后控制面经返回流下推 ControlCommand(撤销/重认证/重采姿态),Agent 上报姿态/ACK。
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, ControlCommand], error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, ControlCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, ControlCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_ChannelClient = grpc.BidiStreamingClient[AgentEvent, ControlCommand]

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
//
// AgentControl 是 Agent↔控制面 的持久双向流(终端实时控制)。
// 权威仍在 PoP(吊销表 + 短 TTL,ZTNA 硬化 L2 3.4 层①③);本通道仅加速端侧反应(层②),best-effort:
// 通道断/丢消息不影响安全——PoP 仍按吊销表+短 TTL 兜底。
type AgentControlServer interface {
	// Channel:Agent 建立长连,首条 AgentEvent{kind=hello,token} 注册身份;
	// 之后控制面经返回流下推 ControlCommand(撤销/重认证/重采姿态),Agent 上报姿态/ACK。
	Channel(grpc.BidiStreamingServer[AgentEvent, ControlCommand]) error
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) Channel(grpc.BidiStreamingServer[AgentEvent, ControlCommand]) error {
	return status.Errorf(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call pancis, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServer).Channel(&grpc.GenericServerStream[AgentEvent, ControlCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_ChannelServer = grpc.BidiStreamingServer[AgentEvent, ControlCommand]

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sase.control.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _AgentControl_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sase/control/v1/control.proto",
}
