// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: sase/control/v1/control.proto

// 包 sase.control.v1:Agent↔控制面 的终端实时控制通道契约(ZTNA 硬化 L2 3.4 层②"端提速")。

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentEvent 是 Agent → 控制面 的消息。
type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`       // hello | posture | ack
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`     // kind=hello:会话凭证(控制面验签确定 tenant/subject/jti)
	Posture string `protobuf:"bytes,3,opt,name=posture,proto3" json:"posture,omitempty"` // kind=posture:设备姿态(如 "compliant" / "non-compliant")
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_control_v1_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sase_control_v1_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_sase_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentEvent) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AgentEvent) GetPosture() string {
	if x != nil {
		return x.Posture
	}
	return ""
}

// ControlCommand 是 控制面 → Agent 的指令。
type ControlCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // revoke | reauth | recheck_posture
	Jti    string `protobuf:"bytes,2,opt,name=jti,proto3" json:"jti,omitempty"`   // kind=revoke:目标凭证 jti(Agent 比对本地会话,命中即弃用)
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_control_v1_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_sase_control_v1_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_sase_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlCommand) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ControlCommand) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *ControlCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_sase_control_v1_control_proto protoreflect.FileDescriptor

var file_sase_control_v1_control_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x61, 0x73, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x73, 0x61, 0x73, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31,
	0x22, 0x50, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x75,
	0x72, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x74, 0x69, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x74, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x32, 0x5b, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x12, 0x4b, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1b, 0x2e,
	0x73, 0x61, 0x73, 0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x61, 0x73,
	0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b,
	0x75, 0x61, 0x69, 0x38, 0x2f, 0x73, 0x61, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x73, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sase_control_v1_control_proto_rawDescOnce sync.Once
	file_sase_control_v1_control_proto_rawDescData = file_sase_control_v1_control_proto_rawDesc
)

func file_sase_control_v1_control_proto_rawDescGZIP() []byte {
	file_sase_control_v1_control_proto_rawDescOnce.Do(func() {
		file_sase_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_sase_control_v1_control_proto_rawDescData)
	})
	return file_sase_control_v1_control_proto_rawDescData
}

var file_sase_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sase_control_v1_control_proto_goTypes = []any{
	(*AgentEvent)(nil),     // 0: sase.control.v1.AgentEvent
	(*ControlCommand)(nil), // 1: sase.control.v1.ControlCommand
}
var file_sase_control_v1_control_proto_depIdxs = []int32{
	0, // 0: sase.control.v1.AgentControl.Channel:input_type -> sase.control.v1.AgentEvent
	1, // 1: sase.control.v1.AgentControl.Channel:output_type -> sase.control.v1.ControlCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sase_control_v1_control_proto_init() }
func file_sase_control_v1_control_proto_init() {
	if File_sase_control_v1_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sase_control_v1_control_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AgentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_control_v1_control_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ControlCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sase_control_v1_control_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sase_control_v1_control_proto_goTypes,
		DependencyIndexes: file_sase_control_v1_control_proto_depIdxs,
		MessageInfos:      file_sase_control_v1_control_proto_msgTypes,
	}.Build()
	File_sase_control_v1_control_proto = out.File
	file_sase_control_v1_control_proto_rawDesc = nil
	file_sase_control_v1_control_proto_goTypes = nil
	file_sase_control_v1_control_proto_depIdxs = nil
}
