// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: sase/xds/v1/policy.proto

// 包 sase.xds.v1:控制面 → PoP 的自定义 xDS 资源契约(单一来源,xDS server L2 3.1 / 编译器 L2 3.9)。

package xdspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyBundleResource 是承载编译态 PolicyBundle 的自定义 xDS 资源(对应 L2 的 L7PolicyBundle)。
// 经 go-control-plane 的 ADS/Delta + 自定义 type URL 下发(type URL:
// type.googleapis.com/sase.xds.v1.PolicyBundleResource)。
//
// 设计取舍:proto 仅作 xDS 信封,payload(compiled)为 api/xdsv1.PolicyBundle 的 JSON 编码 ——
// 复用既有 payload 契约,避免把每个 L7Rule 字段在 proto 里重述(proto 面最小、演进只改信封)。
// 资源名(xDS resource_name)约定为 "tenant/<tenant_id>"(命名空间化,xDS server L2 3.1)。
type PolicyBundleResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 租户
	Version  int64  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                  // bundle 版本(每租户单调)
	Compiled []byte `protobuf:"bytes,3,opt,name=compiled,proto3" json:"compiled,omitempty"`                 // api/xdsv1.PolicyBundle 的 JSON
}

func (x *PolicyBundleResource) Reset() {
	*x = PolicyBundleResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyBundleResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyBundleResource) ProtoMessage() {}

func (x *PolicyBundleResource) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyBundleResource.ProtoReflect.Descriptor instead.
func (*PolicyBundleResource) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyBundleResource) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PolicyBundleResource) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyBundleResource) GetCompiled() []byte {
	if x != nil {
		return x.Compiled
	}
	return nil
}

// RevocationList 是按租户的撤销凭证清单(秒级失效,ZTNA 硬化 L2 3.4 / xDS server L2 3.7)。
// 走与 PolicyBundle 独立的 xDS 流(避免被大 bundle 推送队头阻塞);PoP 验凭证后查此清单,命中即拒。
// type URL:type.googleapis.com/sase.xds.v1.RevocationList,资源名同为 "tenant/<tenant_id>"。
type RevocationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version  int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 信息性版本;增量去重由 xDS 内容哈希负责(非此字段)
	Jtis     []string `protobuf:"bytes,3,rep,name=jtis,proto3" json:"jtis,omitempty"`        // 被撤销的凭证 jti 集
}

func (x *RevocationList) Reset() {
	*x = RevocationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevocationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationList) ProtoMessage() {}

func (x *RevocationList) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationList.ProtoReflect.Descriptor instead.
func (*RevocationList) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *RevocationList) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevocationList) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RevocationList) GetJtis() []string {
	if x != nil {
		return x.Jtis
	}
	return nil
}

// SWGRuleSet 是安全能力 SWG 的 URL 过滤规则集(安全栈 L2,挂 inspect 流量)。
// 经独立 Delta 流下发(复用底座);type URL:type.googleapis.com/sase.xds.v1.SWGRuleSet,资源名 "tenant/<id>"。
type SWGRuleSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string     `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version  int64      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Rules    []*SWGRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *SWGRuleSet) Reset() {
	*x = SWGRuleSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SWGRuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SWGRuleSet) ProtoMessage() {}

func (x *SWGRuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SWGRuleSet.ProtoReflect.Descriptor instead.
func (*SWGRuleSet) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *SWGRuleSet) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SWGRuleSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SWGRuleSet) GetRules() []*SWGRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SWGRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // host | path_prefix
	Pattern string `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Action  string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // block
}

func (x *SWGRule) Reset() {
	*x = SWGRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SWGRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SWGRule) ProtoMessage() {}

func (x *SWGRule) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SWGRule.ProtoReflect.Descriptor instead.
func (*SWGRule) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *SWGRule) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SWGRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SWGRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// FWRuleSet 是安全能力 FWaaS(L3/L4 防火墙,P4)的每租户规则集(安全栈 L2,复用同一下发底座)。
// 经独立 Delta 流下发;type URL:type.googleapis.com/sase.xds.v1.FWRuleSet,资源名 "tenant/<id>"。
// 执行点:PoP 数据面包路径(dptunnel Router 站点间转发前裁决),实现每租户网络分段。
type FWRuleSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string    `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version  int64     `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Rules    []*FWRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *FWRuleSet) Reset() {
	*x = FWRuleSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FWRuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FWRuleSet) ProtoMessage() {}

func (x *FWRuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FWRuleSet.ProtoReflect.Descriptor instead.
func (*FWRuleSet) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *FWRuleSet) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FWRuleSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FWRuleSet) GetRules() []*FWRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// FWRule 是一条 L3/L4 防火墙规则(5 元组匹配,优先级首次匹配;默认拒)。
type FWRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Priority   int32  `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`                         // 越小越先匹配
	Action     string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`                              // allow | deny
	Protocol   string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                          // any | tcp | udp | icmp
	SrcCidr    string `protobuf:"bytes,4,opt,name=src_cidr,json=srcCidr,proto3" json:"src_cidr,omitempty"`             // 源网段(空=any)
	DstCidr    string `protobuf:"bytes,5,opt,name=dst_cidr,json=dstCidr,proto3" json:"dst_cidr,omitempty"`             // 目的网段(空=any)
	DstPortMin uint32 `protobuf:"varint,6,opt,name=dst_port_min,json=dstPortMin,proto3" json:"dst_port_min,omitempty"` // 目的端口范围(0,0 = any)
	DstPortMax uint32 `protobuf:"varint,7,opt,name=dst_port_max,json=dstPortMax,proto3" json:"dst_port_max,omitempty"`
}

func (x *FWRule) Reset() {
	*x = FWRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FWRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FWRule) ProtoMessage() {}

func (x *FWRule) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FWRule.ProtoReflect.Descriptor instead.
func (*FWRule) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *FWRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *FWRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FWRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FWRule) GetSrcCidr() string {
	if x != nil {
		return x.SrcCidr
	}
	return ""
}

func (x *FWRule) GetDstCidr() string {
	if x != nil {
		return x.DstCidr
	}
	return ""
}

func (x *FWRule) GetDstPortMin() uint32 {
	if x != nil {
		return x.DstPortMin
	}
	return 0
}

func (x *FWRule) GetDstPortMax() uint32 {
	if x != nil {
		return x.DstPortMax
	}
	return 0
}

// DLPRuleSet 是安全能力 CASB-DLP(P5)的每租户敏感数据规则集(安全栈 L2,复用同一下发底座)。
// 经独立 Delta 流下发;type URL:type.googleapis.com/sase.xds.v1.DLPRuleSet,资源名 "tenant/<id>"。
// 执行点:PoP L7 inspect(与 SWG 同检查点),命中 block 即拒、命中任意即喂风险引擎(DLP 命中→风险)。
type DLPRuleSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string     `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version  int64      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Rules    []*DLPRule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *DLPRuleSet) Reset() {
	*x = DLPRuleSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DLPRuleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLPRuleSet) ProtoMessage() {}

func (x *DLPRuleSet) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLPRuleSet.ProtoReflect.Descriptor instead.
func (*DLPRuleSet) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *DLPRuleSet) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DLPRuleSet) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DLPRuleSet) GetRules() []*DLPRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// DLPRule 是一条 DLP 规则(关键词/正则匹配敏感数据;action block 阻断、alert 仅告警+喂风险)。
type DLPRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // 规则名(如 "身份证号")
	MatchType string `protobuf:"bytes,2,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"` // keyword | regex
	Pattern   string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`                      // 关键词或正则
	Action    string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                        // block | alert
	Severity  string `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`                    // low | medium | high(喂风险引擎的权重)
}

func (x *DLPRule) Reset() {
	*x = DLPRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DLPRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLPRule) ProtoMessage() {}

func (x *DLPRule) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLPRule.ProtoReflect.Descriptor instead.
func (*DLPRule) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *DLPRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DLPRule) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

func (x *DLPRule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *DLPRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DLPRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// SiteConfig 是 SD-WAN 租户路由域的站点清单(L1 3.8;经 xDS 下发给该租户各 CPE)。
// CPE 据此知道同租户对端站点的子网(把发往这些 CIDR 的流量经 overlay 送 PoP);复用同一下发底座。
type SiteConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId string  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Version  int64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Sites    []*Site `protobuf:"bytes,3,rep,name=sites,proto3" json:"sites,omitempty"`
}

func (x *SiteConfig) Reset() {
	*x = SiteConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SiteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteConfig) ProtoMessage() {}

func (x *SiteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteConfig.ProtoReflect.Descriptor instead.
func (*SiteConfig) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *SiteConfig) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SiteConfig) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SiteConfig) GetSites() []*Site {
	if x != nil {
		return x.Sites
	}
	return nil
}

type Site struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SiteKey string `protobuf:"bytes,1,opt,name=site_key,json=siteKey,proto3" json:"site_key,omitempty"`
	Cidr    string `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Site) Reset() {
	*x = Site{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sase_xds_v1_policy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_sase_xds_v1_policy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_sase_xds_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *Site) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

func (x *Site) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Site) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_sase_xds_v1_policy_proto protoreflect.FileDescriptor

var file_sase_xds_v1_policy_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x61, 0x73, 0x65, 0x2f, 0x78, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x61, 0x73, 0x65,
	0x2e, 0x78, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x69, 0x0a, 0x14, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c,
	0x65, 0x64, 0x22, 0x5b, 0x0a, 0x0e, 0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6a,
	0x74, 0x69, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x74, 0x69, 0x73, 0x22,
	0x6f, 0x0a, 0x0a, 0x53, 0x57, 0x47, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x61, 0x73, 0x65, 0x2e, 0x78, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x57, 0x47, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x22, 0x4f, 0x0a, 0x07, 0x53, 0x57, 0x47, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x6d, 0x0a, 0x09, 0x46, 0x57, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x61, 0x73, 0x65, 0x2e, 0x78, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x57, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73,
	0x22, 0xd2, 0x01, 0x0a, 0x06, 0x46, 0x57, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x72, 0x63, 0x5f, 0x63, 0x69, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x72, 0x63, 0x43, 0x69, 0x64, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x63, 0x69,
	0x64, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x73, 0x74, 0x43, 0x69, 0x64,
	0x72, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6d, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74,
	0x4d, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x64, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x6d, 0x61, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x73, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x4d, 0x61, 0x78, 0x22, 0x6f, 0x0a, 0x0a, 0x44, 0x4c, 0x50, 0x52, 0x75, 0x6c, 0x65,
	0x53, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x75,
	0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x61, 0x73, 0x65,
	0x2e, 0x78, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x4c, 0x50, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x07, 0x44, 0x4c, 0x50, 0x52, 0x75,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x22, 0x6c, 0x0a, 0x0a, 0x53, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x69, 0x74, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x61, 0x73, 0x65, 0x2e, 0x78,
	0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x74, 0x65, 0x52, 0x05, 0x73, 0x69, 0x74, 0x65,
	0x73, 0x22, 0x49, 0x0a, 0x04, 0x53, 0x69, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69, 0x74,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x69, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x34, 0x5a, 0x32,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6b, 0x75, 0x61, 0x69,
	0x38, 0x2f, 0x73, 0x61, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x61, 0x73, 0x65, 0x2f, 0x78, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x78, 0x64, 0x73,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sase_xds_v1_policy_proto_rawDescOnce sync.Once
	file_sase_xds_v1_policy_proto_rawDescData = file_sase_xds_v1_policy_proto_rawDesc
)

func file_sase_xds_v1_policy_proto_rawDescGZIP() []byte {
	file_sase_xds_v1_policy_proto_rawDescOnce.Do(func() {
		file_sase_xds_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(file_sase_xds_v1_policy_proto_rawDescData)
	})
	return file_sase_xds_v1_policy_proto_rawDescData
}

var file_sase_xds_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sase_xds_v1_policy_proto_goTypes = []any{
	(*PolicyBundleResource)(nil), // 0: sase.xds.v1.PolicyBundleResource
	(*RevocationList)(nil),       // 1: sase.xds.v1.RevocationList
	(*SWGRuleSet)(nil),           // 2: sase.xds.v1.SWGRuleSet
	(*SWGRule)(nil),              // 3: sase.xds.v1.SWGRule
	(*FWRuleSet)(nil),            // 4: sase.xds.v1.FWRuleSet
	(*FWRule)(nil),               // 5: sase.xds.v1.FWRule
	(*DLPRuleSet)(nil),           // 6: sase.xds.v1.DLPRuleSet
	(*DLPRule)(nil),              // 7: sase.xds.v1.DLPRule
	(*SiteConfig)(nil),           // 8: sase.xds.v1.SiteConfig
	(*Site)(nil),                 // 9: sase.xds.v1.Site
}
var file_sase_xds_v1_policy_proto_depIdxs = []int32{
	3, // 0: sase.xds.v1.SWGRuleSet.rules:type_name -> sase.xds.v1.SWGRule
	5, // 1: sase.xds.v1.FWRuleSet.rules:type_name -> sase.xds.v1.FWRule
	7, // 2: sase.xds.v1.DLPRuleSet.rules:type_name -> sase.xds.v1.DLPRule
	9, // 3: sase.xds.v1.SiteConfig.sites:type_name -> sase.xds.v1.Site
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sase_xds_v1_policy_proto_init() }
func file_sase_xds_v1_policy_proto_init() {
	if File_sase_xds_v1_policy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sase_xds_v1_policy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PolicyBundleResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RevocationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SWGRuleSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SWGRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FWRuleSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FWRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DLPRuleSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DLPRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SiteConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sase_xds_v1_policy_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Site); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sase_xds_v1_policy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sase_xds_v1_policy_proto_goTypes,
		DependencyIndexes: file_sase_xds_v1_policy_proto_depIdxs,
		MessageInfos:      file_sase_xds_v1_policy_proto_msgTypes,
	}.Build()
	File_sase_xds_v1_policy_proto = out.File
	file_sase_xds_v1_policy_proto_rawDesc = nil
	file_sase_xds_v1_policy_proto_goTypes = nil
	file_sase_xds_v1_policy_proto_depIdxs = nil
}
